### ISSUE TITLE
Système d'utilisateur

### ISSUE THREAD

**Issue by onetrickwolfy** [remib18/webtoon-like#32]
Systeme simple: 
email / nom / password 

- [x] Pop-up Connection (javascript dialog)
- [x] Pop-up Inscription (javascript dialog)
- [x] src/core/rooter.php avec methode access_right()
- [x] Implementation userController 

_Penser à merge de master vers la branche avant de merge sur master._
Je suis parti de hugo/ScriptSQL car la + à jour sur les tables.

**Comment by remib18** [comment]
Javascript dialog

**Comment by onetrickwolfy** [comment]
notes: 
+ dans handler -> verification d'avoir tt les $_POST, puis appel vers core/auth.
+ dans auth: comparaison des données 

Les vérifications seront implémentées plus tard, voir l'issue #39
